root = "."
tmp_dir = "bin"

[build]
cmd = "make"
bin = "./bin/orbit"
full_bin = "./bin/orbit"
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "sh", "makefile"]
exclude_dir = ["static", "tmp", "vendor", "bin", "docs"]
include_dir = []
exclude_file = ["docker-compose.yaml", "docker-compose.yml"]
delay = 1000
stop_on_error = true
log = "air_errors.log"

[misc]
clean_on_exit = true
