services:
  orbit:
    container_name: orbit-web
    build:
      context: .
      dockerfile: air.dockerfile
    restart: unless-stopped
    ports:
      - 5000:80/tcp
    volumes:
      - ".:/app"
    depends_on:
      valkey:
        condition: service_healthy
  valkey:
    container_name: orbit-valkey
    image: valkey/valkey:latest
    restart: unless-stopped
    volumes:
      - ./valkey.conf:/etc/valkey/valkey.conf
      - valkey-data:/data
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  valkey-data:
